name: fdsc2
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy=1.26.*
  - pandas=2.1.*
  #- scipy=1.9.*
  - pytest=7.4.*
  - rasterio=1.3.*
  - matplotlib
  - geopandas=0.14.*
  - openpyxl
  #- numba=0.56.*
  #- cudatoolkit
  #- colorama
  #- pyyaml
  #- xarray=2022.12.*
  #- dask
  #- numbagg
  #- rioxarray=0.13.*
  - xlsxwriter=3.0.*
  - georasters=0.5.* #alternate backend for schu14's pixels_to_points
 
 