channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - rasterio
  - gdal
  - geopandas
  - openpyxl
  - rioxarray
  - xlsxwriter
  - scikit-image
  - xarray
  - tqdm
  - pytest
  - pip
 
 
    
 
